# Generated by Django 6.1 on 2026-09-02 14:56

import django.db.models.deletion
import django.utils.timezone
import queue_store.fields
import queue_store.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('label', models.CharField(max_length=20, unique=True, verbose_name='年齢帯')),
            ],
            options={
                'verbose_name': '年齢帯',
                'verbose_name_plural': '年齢帯',
                'ordering': ['display_order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClinicClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='休診日')),
                ('reason', models.CharField(blank=True, max_length=100, verbose_name='理由')),
            ],
            options={
                'verbose_name': '臨時休診日',
                'verbose_name_plural': '臨時休診日',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ClinicSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, '月曜日'), (1, '火曜日'), (2, '水曜日'), (3, '木曜日'), (4, '金曜日'), (5, '土曜日'), (6, '日曜日')], unique=True, verbose_name='曜日')),
                ('is_closed', models.BooleanField(default=False, verbose_name='休診日')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='受付開始')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='受付終了')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='昼休み開始')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='昼休み終了')),
            ],
            options={
                'verbose_name': '受付時間',
                'verbose_name_plural': '受付時間',
                'ordering': ['weekday'],
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('code', models.SlugField(max_length=20, unique=True, verbose_name='コード')),
                ('label', models.CharField(max_length=20, verbose_name='性別')),
            ],
            options={
                'verbose_name': '性別',
                'verbose_name_plural': '性別',
                'ordering': ['display_order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='コード')),
                ('name', models.CharField(max_length=60, verbose_name='症状')),
            ],
            options={
                'verbose_name': '症状',
                'verbose_name_plural': '症状',
                'ordering': ['display_order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='一時識別子')),
                ('full_name', queue_store.fields.EncryptedTextField(verbose_name='氏名')),
                ('kana', queue_store.fields.EncryptedTextField(verbose_name='フリガナ')),
                ('free_text', queue_store.fields.EncryptedTextField(blank=True, default='', verbose_name='自由記述')),
                ('visit_type', models.CharField(choices=[('reserved', '予約'), ('walk_in', '飛び込み')], max_length=16, verbose_name='来院区分')),
                ('reserved_at', models.DateTimeField(blank=True, null=True, verbose_name='予約時刻')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='問診票提出')),
                ('status', models.CharField(choices=[('waiting', '待機中'), ('in_exam', '診察中'), ('done', '診察終了')], default='waiting', max_length=16, verbose_name='状態')),
                ('exam_started_at', models.DateTimeField(blank=True, null=True, verbose_name='診察開始')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='診察完了')),
                ('age_band', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='queue_store.ageband', verbose_name='年齢帯')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='queue_store.gender', verbose_name='性別')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='queue_store.symptom', verbose_name='症状')),
            ],
            options={
                'verbose_name': '待機列のエントリ',
                'verbose_name_plural': '待機列のエントリ',
                'ordering': ['submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationRoomState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('is_in_exam', models.BooleanField(default=False, verbose_name='診察中')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='診察開始')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='直近の診察完了')),
                ('current_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='queue_store.queueentry', verbose_name='診察中の患者')),
            ],
            options={
                'verbose_name': '診察室の状態',
                'verbose_name_plural': '診察室の状態',
            },
        ),
        migrations.CreateModel(
            name='SymptomDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.PositiveIntegerField(default=queue_store.models.default_duration_minutes, verbose_name='所要時間（分）')),
                ('sample_count', models.PositiveIntegerField(default=0, verbose_name='実測件数')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('symptom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='duration', to='queue_store.symptom', verbose_name='症状')),
            ],
            options={
                'verbose_name': '所要時間（Duration Table）',
                'verbose_name_plural': '所要時間（Duration Table）',
                'ordering': ['symptom__display_order', 'symptom__pk'],
            },
        ),
        migrations.CreateModel(
            name='UnregisteredSymptomAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_minutes', models.PositiveIntegerField(verbose_name='適用した既定の所要時間（分）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='検出日時')),
                ('acknowledged', models.BooleanField(default=False, verbose_name='確認済み')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='確認日時')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unregistered_alerts', to='queue_store.queueentry', verbose_name='対象の患者')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unregistered_alerts', to='queue_store.symptom', verbose_name='症状')),
            ],
            options={
                'verbose_name': '未登録症状アラート',
                'verbose_name_plural': '未登録症状アラート',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='queueentry',
            index=models.Index(fields=['status', 'visit_type'], name='queue_status_visit_idx'),
        ),
        migrations.AddIndex(
            model_name='queueentry',
            index=models.Index(fields=['reserved_at'], name='queue_reserved_at_idx'),
        ),
        migrations.AddIndex(
            model_name='queueentry',
            index=models.Index(fields=['submitted_at'], name='queue_submitted_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='queueentry',
            constraint=models.CheckConstraint(condition=models.Q(('visit_type', 'walk_in'), models.Q(('reserved_at__isnull', False), ('visit_type', 'reserved')), _connector='OR'), name='reserved_visit_requires_reserved_at'),
        ),
    ]
