# Generated by Django 6.1 on 2026-09-04 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('queue_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('final_call', '確定呼出')], max_length=20, verbose_name='種別')),
                ('channel', models.CharField(choices=[('web_push', 'Web Push'), ('in_page', '画面内表示')], max_length=20, verbose_name='経路')),
                ('status', models.CharField(choices=[('sent', '送信済み'), ('failed', '送信失敗')], default='sent', max_length=20, verbose_name='結果')),
                ('detail', models.CharField(blank=True, max_length=200, verbose_name='補足')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='送信日時')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='queue_store.queueentry', verbose_name='対象患者')),
            ],
            options={
                'verbose_name': '通知記録',
                'verbose_name_plural': '通知記録',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('entry', 'kind'), name='unique_notification_per_entry')],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, unique=True, verbose_name='エンドポイント')),
                ('p256dh', models.CharField(max_length=255, verbose_name='公開鍵')),
                ('auth', models.CharField(max_length=255, verbose_name='認証シークレット')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='queue_store.queueentry', verbose_name='対象患者')),
            ],
            options={
                'verbose_name': 'プッシュ購読',
                'verbose_name_plural': 'プッシュ購読',
                'indexes': [models.Index(fields=['entry'], name='notifier_pu_entry_i_a4877a_idx')],
            },
        ),
    ]
